[package]
name = "fst-reader"
version = "0.8.7"
edition = "2021"
authors = ["Kevin Laeufer <laeufer@berkeley.edu>"]
description = "FST wavedump format reader implemented in safe Rust. Formerly known as fst-native."
homepage = "https://github.com/ekiwi/fst-reader"
license = "BSD-3-Clause"
include = ["Cargo.toml", "LICENSE", "src/", "tests/", "examples/"]
keywords = ["fst", "waveform", "wavedump"]

[dependencies]
lz4_flex = "0.11"
flate2 = "1.0"
num_enum = "0.7"
thiserror = "2.0"

[dev-dependencies]
clap = { version = "4.x", features = ["derive"] }
fst-sys = "0.2.0"
leb128 = "0.2.5"
proptest = "1.x"
proptest-derive = "0.5"
vcd = "0.7"

